ViewModels/PasswordChangeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace IdentityServerExample.ViewModels
{
    public class PasswordChangeViewModel
    {
        [Display(Name = "Eski Şifre")]
        [Required(ErrorMessage = "Eski şifreniz gereklidir")]
        public string PasswordOld { get; set; }

        [Display(Name = "Yeni Şifre")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Yeni şifreniz gereklidir")]

        public string PasswordNew { get; set; }

        [Display(Name = "Yeni Şifre Tekrar")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Yeni şifreniz tekrarı gereklidir")]
        [Compare("PasswordNew", ErrorMessage = "Yeni şifre tekrarı doğru değildir")]
        public string PasswordConfirm { get; set; }

    }
}

Controllers/AdminController.cs
using IdentityServerExample.Models;
using IdentityServerExample.ViewModels;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityServerExample.Controllers
{
  
    public class AdminController : BaseController
    {
        public AdminController(UserManager<User> userManager, RoleManager<UserRole> roleManager) : base(userManager, null, roleManager)
        {

        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Users()
        {
            return View(_userManager.Users.ToList());
        }

        public IActionResult RoleCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RoleCreate(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                UserRole userRole = new UserRole();

                userRole.Name = roleViewModel.Name;


                IdentityResult identityResult = await _roleManager.CreateAsync(userRole);

                if (identityResult.Succeeded)
                    return RedirectToAction("Roles");
                else
                {
                    AddModelError(identityResult);
                    return View(roleViewModel);
                }
            }
            else
                return View(roleViewModel);
        }

        public IActionResult Roles()
        {
            return View(_roleManager.Roles.ToList());
        }

        public async Task<IActionResult> RolDelete(string id)
        {
            UserRole userRole = await _roleManager.FindByIdAsync(id);
            if (userRole != null)
            {
                IdentityResult identityResult = await _roleManager.DeleteAsync(userRole);

                if (identityResult.Succeeded)
                    return RedirectToAction("Index");
                else
                    ViewBag.Error = "Hata Medana Geldi";

            }
            return RedirectToAction("Roles");
        }

        public async Task<IActionResult> RolEdit(string id)
        {
            UserRole userRole = await _roleManager.FindByIdAsync(id);
            return View(userRole.Adapt<RoleViewModel>());
        }

        [HttpPost]
        public async Task<IActionResult> RolEdit(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                UserRole userRole = await _roleManager.FindByIdAsync(roleViewModel.Id.ToString());

                if (userRole != null)
                {
                    userRole.Name = roleViewModel.Name;
                    IdentityResult identityResult = await _roleManager.UpdateAsync(userRole);

                    if (identityResult.Succeeded)
                        return RedirectToAction("Roles");
                    else

                        ViewBag.Error = "Hata oluştu";
                }
                return View(roleViewModel);
            }
            else
                return View(roleViewModel);
        }

        public async Task<IActionResult> RolAssign(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            List<RoleAssignViewModel> roleAssignViewModels = new List<RoleAssignViewModel>();

            TempData["UserId"] = id;

            ViewBag.UserName = user.UserName;
            IQueryable<UserRole> _roles = _roleManager.Roles;

            IList<string> _userRol = await getUserRole(user);

            foreach (var role in _roles)
            {
                if (_userRol.Contains(role.Name))
                    roleAssignViewModels.Add(new RoleAssignViewModel { RoleName = role.Name, RoleId = role.Id, Exits = true });
                else
                    roleAssignViewModels.Add(new RoleAssignViewModel { RoleName = role.Name, RoleId = role.Id, Exits = false });
            }
            return View(roleAssignViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> RolAssign(List<RoleAssignViewModel> roleAssignViewModel)
        {

            User _user = await _userManager.FindByIdAsync(TempData["UserId"].ToString());
            foreach (var item in roleAssignViewModel)
            {

                if (item.Exits)
                    await _userManager.AddToRoleAsync(_user, item.RoleName);
                else
                    await _userManager.RemoveFromRoleAsync(_user, item.RoleName);
            }

            return RedirectToAction("Users");
        }

        public IActionResult Claims()
        {
            return View(User.Claims.ToList());
        }
    }
}

Controllers/MemberController.cs
using IdentityServerExample.Enums;
using IdentityServerExample.Models;
using IdentityServerExample.ViewModels;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Threading.Tasks;

namespace IdentityServerExample.Controllers
{
    [Authorize]
    public class MemberController : BaseController
    {

        public MemberController(UserManager<User> userManager, SignInManager<User> signInManager) : base(userManager, signInManager)
        {

        }

        public async Task<IActionResult> Index()
        {
            User user = await this.CurrentUser;

            if (user != null)
            {
                if (string.IsNullOrEmpty(user.PictureUrl))
                    user.PictureUrl = "/NoPicture.png";
            }

            //mapster kütüphanesi automappper dan daha küçük map kütüphanesidir.

            UserViewModel userViewModel = user.Adapt<UserViewModel>();

            return View(userViewModel);
        }

        public async Task<IActionResult> UserEdit()
        {
            User user = await this.CurrentUser;
            UserViewModel userViewModel = user.Adapt<UserViewModel>();

            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));
            return View(userViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(UserViewModel userViewModel, IFormFile userPicture)
        {
            try
            {
                ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));
                //password alanının validation özelliğine takılmaması için 
                ModelState.Remove("Password");
                if (ModelState.IsValid)
                {
                    User user = await this.CurrentUser;
                    if (userPicture != null && userPicture.Length > 0)
                    {
                        var fileName = Guid.NewGuid().ToString() + Path.GetExtension(userPicture.FileName);

                        var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/UserPicture", fileName);

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await userPicture.CopyToAsync(stream);
                            user.PictureUrl = fileName;
                        }
                    }

                    user.UserName = userViewModel.UserName;
                    user.Email = userViewModel.Email;
                    user.PhoneNumber = userViewModel.PhoneNumber;
                    user.City = userViewModel.City;
                    user.BirthDay = userViewModel.BirthDay;
                    user.Gender = (int)userViewModel.Gender;


                    IdentityResult identityResult = await _userManager.UpdateAsync(user);
                    if (identityResult.Succeeded)
                    {
                        //username değiştiği için stamp ayarını değiştiriyoruz 

                        ViewBag.success = "true";
                        await _userManager.UpdateSecurityStampAsync(user);

                        await _signInManager.SignOutAsync();
                        await _signInManager.SignInAsync(user, true);
                    }
                    else
                        AddModelError(identityResult);

                }
                return View(userViewModel);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(userViewModel);
            }
        }

        public IActionResult PasswordChange()
        {
            return View(); ;
        }

        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeViewModel passwordChangeViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    User user = await this.CurrentUser;

                    if (await _userManager.CheckPasswordAsync(user, passwordChangeViewModel.PasswordOld))
                    {
                        IdentityResult identityResult = await _userManager.ChangePasswordAsync(user, passwordChangeViewModel.PasswordOld, passwordChangeViewModel.PasswordNew);
                        if (identityResult.Succeeded)
                        {
                            ViewBag.Success = "true";
                            //eski şifreyle dolaşmasını engellemek için session süresini beklemeden 
                            await _userManager.UpdateSecurityStampAsync(user);


                            await _signInManager.SignOutAsync();
                            //ispersisten 
                            await _signInManager.PasswordSignInAsync(user, passwordChangeViewModel.PasswordNew, true, false);

                        }
                        else
                            AddModelError(identityResult);
                    }
                    else
                        ModelState.AddModelError("", "Eksi şifreniz doğru değildir");
                }
                return View(passwordChangeViewModel);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(passwordChangeViewModel);
            }
        }

        ////klasik yöntemle
        //public async Task<IActionResult> LogOut()
        //{
        //    await _signInManager.SignOutAsync();
        //    //klasik yöntem 
        //    return RedirectToAction("Index", "Home");

        //} 

        public async void LogOut()
        {
            await _signInManager.SignOutAsync();

        }
        public IActionResult AccessDenied()
        {
            return View();
        }

        [Authorize("editor")]
        public IActionResult Editor()
        {
            return View();
        }


        [Authorize("mananger")]
        public IActionResult Manager()
        {
            return View();
        }

        [Authorize(Policy = "AnkaraPolicy")]
        public IActionResult Ankara()
        {
            return View();
        }
    }
}

Views/Member/AccessDenied.cshtml

@{
    ViewData["Title"] = "AccessDenied";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Bu sayfaya erişim iziniz yoktur.</h1>


Views/Member/Ankara.cshtml

@{
    ViewData["Title"] = "Ankara";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Ankara</h1>


Views/Member/Editor.cshtml

@{
    ViewData["Title"] = "Editor";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Editor Sayafasına hoş geldiniz</h1>


Views/Member/Index.cshtml
@model UserViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}


<h3 class="text-center">Kullanıcı Bilgileri</h3>
<div class="row">
    <div class="col-sm-3">
        <img src="~/UserPicture/@Model.PictureUrl" style="width:100%; height:100%" />
    </div>
    <div class="col-sm-9">
        <table class="table table-bordered table-striped">
            <tr>
                <td>Kullanıcı ismi</td>
                <td>@Model.UserName</td>
            </tr>

            <tr>
                <td>Kullanıcı Email</td>
                <td>@Model.Email</td>
            </tr>

            <tr>
                <td>Telefon No</td>
                <td>@Model.PhoneNumber</td>
            </tr>

            <tr>
                <td>İl</td>
                <td>
                    @if (!String.IsNullOrEmpty(Model.City))
                    {
                        @Model.City
                    }
                    else
                    {
                        <span>Belirtilmemiş</span>
                    }

                </td>
            </tr>

            <tr>
                <td>Doğum Tarihi</td>
                <td>


                    @if (@Model.BirthDay != null)
                    {
                        @Model.BirthDay?.ToShortDateString()
                    }
                    else
                    {
                        <span>Belirtilmemiş</span>
                    } 
                </td>
            </tr>

            <tr>
                <td>Cinsiyeti</td>
                <td>
                    @Model.Gender
            </td>
        </tr>

    </table>

</div>

</div>

Views/Member/Manager.cshtml

@{
    ViewData["Title"] = "Manager";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Manager sayfasına hoş geldiniz</h1>


Views/Member/PasswordChange.cshtml
@model IdentityServerExample.ViewModels.PasswordChangeViewModel

@{
    ViewData["Title"] = "PasswordChange";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

@if (ViewBag.Success == "true")
{
    <div class="alert alert-info">Şifre değiştirme işleminiz gerçekleştirilmiştir.</div>
}
else
{

    <div class="row">
        <div class="col-md-4">
            <form asp-action="PasswordChange">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="PasswordOld" class="control-label"></label>
                    <input asp-for="PasswordOld" class="form-control" />
                    <span asp-validation-for="PasswordOld" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PasswordNew" class="control-label"></label>
                    <input asp-for="PasswordNew" class="form-control" />
                    <span asp-validation-for="PasswordNew" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PasswordConfirm" class="control-label"></label>
                    <input asp-for="PasswordConfirm" class="form-control" />
                    <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Şifre Değiştir" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}



Views/Member/UserEdit.cshtml
@model IdentityServerExample.ViewModels.UserViewModel

@{
    ViewData["Title"] = "Kullanıcı Bilgileri Değiştirme";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

@if (ViewBag.Success == "true")
{
    <div class="alert alert-info">Bilgileriniz güncellenmiştir.</div>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <form asp-action="UserEdit" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BirthDay" class="control-label"></label>
                    <input asp-for="BirthDay" class="form-control" />
                    <span asp-validation-for="BirthDay" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Gender" class="control-label"></label>
                    <select class="form-control" asp-for="Gender" asp-items="ViewBag.Gender"> </select>
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="form-label">Resim</label>
                    <input type="file" class="form-control" name="userPicture" />
                </div>             
                <div class="form-group">
                    <input type="submit" value="Kullanıcı Bilgileri Güncelle" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}



Views/Member/_MemberLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">IdentityServer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-action="Index" asp-controller="Member">Üye Ana Sayfa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Admin">Admin Ana Sayfa</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Member">Editor Ana Sayfa</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Member">Manager Ana Sayfa</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-action="Ankara" asp-controller="Member">Ankara Ana Sayfa</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="margin-top:10px">
        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3">
                <h3>Menü</h3>
                <a class="btn btn-info btn-block" asp-action="PasswordChange" asp-controller="Member">Şifre değiştirme</a>

                <a class="btn btn-info btn-block" asp-action="UserEdit" asp-controller="Member">Kullanıcı bilgisi güncelleme</a>

                <a class="btn btn-info btn-block" asp-action="LogOut" asp-controller="Member" asp-route-returnUrl="/Home/Index">Çıkış yap</a>
            </div>
        </div>

    </div>
</body>
</html>